app = "fastapi-book-project-icy-surf-8769"
primary_region = "lhr"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.headers.response]
    override = { "Server" = "nginx" }

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[processes]
app = "supervisord -c /etc/supervisor/supervisord.conf -n"
