# fly.toml app configuration file generated for fastapi-book-project-icy-surf-8769 on 2025-02-12T01:43:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastapi-book-project-icy-surf-8769'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
app = "supervisord -c /etc/supervisor/supervisord.conf -n"
