name: Railway Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy to Railway
    runs-on: ubuntu-latest
    concurrency: deploy-group  # Ensures only one deployment runs at a time
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy application to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Confirm deployment success
        run: echo "Deployment successful!"
