name: CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH=$HOME/.fly/bin:$PATH
          flyctl version

      - name: Verify FLY_API_TOKEN
        run: |
          if [ -z "${{ secrets.FLY_API_TOKEN }}" ]; then
            echo "FLY_API_TOKEN is not set. Please configure it in GitHub Secrets."
            exit 1
          fi

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --remote-only
